# -*- coding: utf-8 -*-
"""list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N2E7UjOUWbCYIxB73p4yOzt1NiXSUkCa
"""

list=[1,2,3,4,5]
print(list)

list=['hello','world']
print(list)

a=[1,2,3]
b='hello'
c=[]
print(c,b,a)

t=['a','b','c','d','e','r']
t[1:3]

t[:4]

t[3:]

a=[1,2,3]
b=a[:]
print(b)

