# -*- coding: utf-8 -*-
"""list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N2E7UjOUWbCYIxB73p4yOzt1NiXSUkCa
"""

list=[1,2,3,4,5]
print(list)

list=['hello','world']
print(list)

a=[1,2,3]
b='hello'
c=[]
print(c,b,a)

t=['a','b','c','d','e','r']
t[1:3]

t[:4]

t[3:]

a=[1,2,3]
b=a[:]
print(b)

d={1:'geeks',2:'for',3:'geeks'}
print(d)

my_list=[1,'hello',3.14,True]
print("original list:",my_list)

my_list.append('world')
print("list after appending 'world':",my_list)

my_list.remove(3.14)
print("list after removing 3.14:",my_list)

my_tuple=(1,'apple',3.14,False)
print("original tuple:",my_tuple)

print("first element:",my_tuple[0])
print("last element:",my_tuple[-1])

#while
i=1
while i<=5:
    print(i)
    i+=1

#for
for i in range(1,6):
    print(i)

#conditional statements
num=int(input("enter a number:"))
if num>0:
    print(num,"is positive")
elif num<0:
    print(num,"is negative")
else:
    print("the number is zero")

def greet(name):
  """This function takes the  name as an argument and prints a greeting message"""
  print(f"hello from function,{name}!")
greet("Alice")#calling function

def helloworld(name):
  print(f"hello from {name}")
a =helloworld("lilly")
print(a)

